// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: connection/v1/connected_devices.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionError int32

const (
	ConnectionError_CONNECTION_ERROR_UNKNOWN               ConnectionError = 0
	ConnectionError_CONNECTION_ERROR_HUB_NOT_AUTHENTICATED ConnectionError = 1
	ConnectionError_CONNECTION_ERROR_INTERNAL              ConnectionError = 2
)

// Enum value maps for ConnectionError.
var (
	ConnectionError_name = map[int32]string{
		0: "CONNECTION_ERROR_UNKNOWN",
		1: "CONNECTION_ERROR_HUB_NOT_AUTHENTICATED",
		2: "CONNECTION_ERROR_INTERNAL",
	}
	ConnectionError_value = map[string]int32{
		"CONNECTION_ERROR_UNKNOWN":               0,
		"CONNECTION_ERROR_HUB_NOT_AUTHENTICATED": 1,
		"CONNECTION_ERROR_INTERNAL":              2,
	}
)

func (x ConnectionError) Enum() *ConnectionError {
	p := new(ConnectionError)
	*p = x
	return p
}

func (x ConnectionError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionError) Descriptor() protoreflect.EnumDescriptor {
	return file_connection_v1_connected_devices_proto_enumTypes[0].Descriptor()
}

func (ConnectionError) Type() protoreflect.EnumType {
	return &file_connection_v1_connected_devices_proto_enumTypes[0]
}

func (x ConnectionError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionError.Descriptor instead.
func (ConnectionError) EnumDescriptor() ([]byte, []int) {
	return file_connection_v1_connected_devices_proto_rawDescGZIP(), []int{0}
}

type ConnectDeviceRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Device secret used for authentication.
	// Every device must have secret from which it generates 30s last auth key, thats checked on cloud.
	DeviceKey     string `protobuf:"bytes,2,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectDeviceRequest) Reset() {
	*x = ConnectDeviceRequest{}
	mi := &file_connection_v1_connected_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDeviceRequest) ProtoMessage() {}

func (x *ConnectDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connected_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDeviceRequest.ProtoReflect.Descriptor instead.
func (*ConnectDeviceRequest) Descriptor() ([]byte, []int) {
	return file_connection_v1_connected_devices_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ConnectDeviceRequest) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

type ConnectDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Error         *ConnectionError       `protobuf:"varint,2,opt,name=error,proto3,enum=connection.v1.ConnectionError,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectDeviceResponse) Reset() {
	*x = ConnectDeviceResponse{}
	mi := &file_connection_v1_connected_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDeviceResponse) ProtoMessage() {}

func (x *ConnectDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connected_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDeviceResponse.ProtoReflect.Descriptor instead.
func (*ConnectDeviceResponse) Descriptor() ([]byte, []int) {
	return file_connection_v1_connected_devices_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectDeviceResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ConnectDeviceResponse) GetError() ConnectionError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ConnectionError_CONNECTION_ERROR_UNKNOWN
}

var File_connection_v1_connected_devices_proto protoreflect.FileDescriptor

const file_connection_v1_connected_devices_proto_rawDesc = "" +
	"\n" +
	"%connection/v1/connected_devices.proto\x12\rconnection.v1\"R\n" +
	"\x14ConnectDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"device_key\x18\x02 \x01(\tR\tdeviceKey\"x\n" +
	"\x15ConnectDeviceResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x129\n" +
	"\x05error\x18\x02 \x01(\x0e2\x1e.connection.v1.ConnectionErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error*z\n" +
	"\x0fConnectionError\x12\x1c\n" +
	"\x18CONNECTION_ERROR_UNKNOWN\x10\x00\x12*\n" +
	"&CONNECTION_ERROR_HUB_NOT_AUTHENTICATED\x10\x01\x12\x1d\n" +
	"\x19CONNECTION_ERROR_INTERNAL\x10\x02B3Z1github.com/ship-monitor/protocol/go/connection/v1b\x06proto3"

var (
	file_connection_v1_connected_devices_proto_rawDescOnce sync.Once
	file_connection_v1_connected_devices_proto_rawDescData []byte
)

func file_connection_v1_connected_devices_proto_rawDescGZIP() []byte {
	file_connection_v1_connected_devices_proto_rawDescOnce.Do(func() {
		file_connection_v1_connected_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connection_v1_connected_devices_proto_rawDesc), len(file_connection_v1_connected_devices_proto_rawDesc)))
	})
	return file_connection_v1_connected_devices_proto_rawDescData
}

var file_connection_v1_connected_devices_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_connection_v1_connected_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_connection_v1_connected_devices_proto_goTypes = []any{
	(ConnectionError)(0),          // 0: connection.v1.ConnectionError
	(*ConnectDeviceRequest)(nil),  // 1: connection.v1.ConnectDeviceRequest
	(*ConnectDeviceResponse)(nil), // 2: connection.v1.ConnectDeviceResponse
}
var file_connection_v1_connected_devices_proto_depIdxs = []int32{
	0, // 0: connection.v1.ConnectDeviceResponse.error:type_name -> connection.v1.ConnectionError
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_connection_v1_connected_devices_proto_init() }
func file_connection_v1_connected_devices_proto_init() {
	if File_connection_v1_connected_devices_proto != nil {
		return
	}
	file_connection_v1_connected_devices_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connection_v1_connected_devices_proto_rawDesc), len(file_connection_v1_connected_devices_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connection_v1_connected_devices_proto_goTypes,
		DependencyIndexes: file_connection_v1_connected_devices_proto_depIdxs,
		EnumInfos:         file_connection_v1_connected_devices_proto_enumTypes,
		MessageInfos:      file_connection_v1_connected_devices_proto_msgTypes,
	}.Build()
	File_connection_v1_connected_devices_proto = out.File
	file_connection_v1_connected_devices_proto_goTypes = nil
	file_connection_v1_connected_devices_proto_depIdxs = nil
}
