// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: connection/v1/connected_devices.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectDeviceRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Device secret used for authentication.
	// Every device must have secret from which it generates 30s last auth key, thats checked on cloud.
	DeviceKey     string `protobuf:"bytes,2,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectDeviceRequest) Reset() {
	*x = ConnectDeviceRequest{}
	mi := &file_connection_v1_connected_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDeviceRequest) ProtoMessage() {}

func (x *ConnectDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connected_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDeviceRequest.ProtoReflect.Descriptor instead.
func (*ConnectDeviceRequest) Descriptor() ([]byte, []int) {
	return file_connection_v1_connected_devices_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ConnectDeviceRequest) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

type ConnectDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectDeviceResponse) Reset() {
	*x = ConnectDeviceResponse{}
	mi := &file_connection_v1_connected_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDeviceResponse) ProtoMessage() {}

func (x *ConnectDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connected_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDeviceResponse.ProtoReflect.Descriptor instead.
func (*ConnectDeviceResponse) Descriptor() ([]byte, []int) {
	return file_connection_v1_connected_devices_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectDeviceResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

var File_connection_v1_connected_devices_proto protoreflect.FileDescriptor

const file_connection_v1_connected_devices_proto_rawDesc = "" +
	"\n" +
	"%connection/v1/connected_devices.proto\x12\rconnection.v1\"R\n" +
	"\x14ConnectDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"device_key\x18\x02 \x01(\tR\tdeviceKey\"3\n" +
	"\x15ConnectDeviceResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapprovedB3Z1github.com/ship-monitor/protocol/go/connection/v1b\x06proto3"

var (
	file_connection_v1_connected_devices_proto_rawDescOnce sync.Once
	file_connection_v1_connected_devices_proto_rawDescData []byte
)

func file_connection_v1_connected_devices_proto_rawDescGZIP() []byte {
	file_connection_v1_connected_devices_proto_rawDescOnce.Do(func() {
		file_connection_v1_connected_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connection_v1_connected_devices_proto_rawDesc), len(file_connection_v1_connected_devices_proto_rawDesc)))
	})
	return file_connection_v1_connected_devices_proto_rawDescData
}

var file_connection_v1_connected_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_connection_v1_connected_devices_proto_goTypes = []any{
	(*ConnectDeviceRequest)(nil),  // 0: connection.v1.ConnectDeviceRequest
	(*ConnectDeviceResponse)(nil), // 1: connection.v1.ConnectDeviceResponse
}
var file_connection_v1_connected_devices_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_connection_v1_connected_devices_proto_init() }
func file_connection_v1_connected_devices_proto_init() {
	if File_connection_v1_connected_devices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connection_v1_connected_devices_proto_rawDesc), len(file_connection_v1_connected_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connection_v1_connected_devices_proto_goTypes,
		DependencyIndexes: file_connection_v1_connected_devices_proto_depIdxs,
		MessageInfos:      file_connection_v1_connected_devices_proto_msgTypes,
	}.Build()
	File_connection_v1_connected_devices_proto = out.File
	file_connection_v1_connected_devices_proto_goTypes = nil
	file_connection_v1_connected_devices_proto_depIdxs = nil
}
