// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: connection/v1/hub_auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access token to put in `Authorization` header.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Refresh token to use in authentication refresh.
	RefreshToken  string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthData) Reset() {
	*x = AuthData{}
	mi := &file_connection_v1_hub_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthData) ProtoMessage() {}

func (x *AuthData) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_hub_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthData.ProtoReflect.Descriptor instead.
func (*AuthData) Descriptor() ([]byte, []int) {
	return file_connection_v1_hub_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthData) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthData) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type AuthenticateHubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hub identifier. It should be generated on hub.
	HubId         string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Model         string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateHubRequest) Reset() {
	*x = AuthenticateHubRequest{}
	mi := &file_connection_v1_hub_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateHubRequest) ProtoMessage() {}

func (x *AuthenticateHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_hub_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateHubRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateHubRequest) Descriptor() ([]byte, []int) {
	return file_connection_v1_hub_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateHubRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *AuthenticateHubRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type AuthenticateHubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *AuthData              `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateHubResponse) Reset() {
	*x = AuthenticateHubResponse{}
	mi := &file_connection_v1_hub_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateHubResponse) ProtoMessage() {}

func (x *AuthenticateHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_hub_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateHubResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateHubResponse) Descriptor() ([]byte, []int) {
	return file_connection_v1_hub_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateHubResponse) GetAuth() *AuthData {
	if x != nil {
		return x.Auth
	}
	return nil
}

type RefreshHubAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshHubAuthRequest) Reset() {
	*x = RefreshHubAuthRequest{}
	mi := &file_connection_v1_hub_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshHubAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshHubAuthRequest) ProtoMessage() {}

func (x *RefreshHubAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_hub_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshHubAuthRequest.ProtoReflect.Descriptor instead.
func (*RefreshHubAuthRequest) Descriptor() ([]byte, []int) {
	return file_connection_v1_hub_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshHubAuthRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshHubAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *AuthData              `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshHubAuthResponse) Reset() {
	*x = RefreshHubAuthResponse{}
	mi := &file_connection_v1_hub_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshHubAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshHubAuthResponse) ProtoMessage() {}

func (x *RefreshHubAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_hub_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshHubAuthResponse.ProtoReflect.Descriptor instead.
func (*RefreshHubAuthResponse) Descriptor() ([]byte, []int) {
	return file_connection_v1_hub_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshHubAuthResponse) GetAuth() *AuthData {
	if x != nil {
		return x.Auth
	}
	return nil
}

var File_connection_v1_hub_auth_proto protoreflect.FileDescriptor

const file_connection_v1_hub_auth_proto_rawDesc = "" +
	"\n" +
	"\x1cconnection/v1/hub_auth.proto\x12\rconnection.v1\"R\n" +
	"\bAuthData\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"E\n" +
	"\x16AuthenticateHubRequest\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\tR\x05hubId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"F\n" +
	"\x17AuthenticateHubResponse\x12+\n" +
	"\x04auth\x18\x01 \x01(\v2\x17.connection.v1.AuthDataR\x04auth\"<\n" +
	"\x15RefreshHubAuthRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"E\n" +
	"\x16RefreshHubAuthResponse\x12+\n" +
	"\x04auth\x18\x01 \x01(\v2\x17.connection.v1.AuthDataR\x04authB3Z1github.com/ship-monitor/protocol/go/connection/v1b\x06proto3"

var (
	file_connection_v1_hub_auth_proto_rawDescOnce sync.Once
	file_connection_v1_hub_auth_proto_rawDescData []byte
)

func file_connection_v1_hub_auth_proto_rawDescGZIP() []byte {
	file_connection_v1_hub_auth_proto_rawDescOnce.Do(func() {
		file_connection_v1_hub_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connection_v1_hub_auth_proto_rawDesc), len(file_connection_v1_hub_auth_proto_rawDesc)))
	})
	return file_connection_v1_hub_auth_proto_rawDescData
}

var file_connection_v1_hub_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_connection_v1_hub_auth_proto_goTypes = []any{
	(*AuthData)(nil),                // 0: connection.v1.AuthData
	(*AuthenticateHubRequest)(nil),  // 1: connection.v1.AuthenticateHubRequest
	(*AuthenticateHubResponse)(nil), // 2: connection.v1.AuthenticateHubResponse
	(*RefreshHubAuthRequest)(nil),   // 3: connection.v1.RefreshHubAuthRequest
	(*RefreshHubAuthResponse)(nil),  // 4: connection.v1.RefreshHubAuthResponse
}
var file_connection_v1_hub_auth_proto_depIdxs = []int32{
	0, // 0: connection.v1.AuthenticateHubResponse.auth:type_name -> connection.v1.AuthData
	0, // 1: connection.v1.RefreshHubAuthResponse.auth:type_name -> connection.v1.AuthData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_connection_v1_hub_auth_proto_init() }
func file_connection_v1_hub_auth_proto_init() {
	if File_connection_v1_hub_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connection_v1_hub_auth_proto_rawDesc), len(file_connection_v1_hub_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connection_v1_hub_auth_proto_goTypes,
		DependencyIndexes: file_connection_v1_hub_auth_proto_depIdxs,
		MessageInfos:      file_connection_v1_hub_auth_proto_msgTypes,
	}.Build()
	File_connection_v1_hub_auth_proto = out.File
	file_connection_v1_hub_auth_proto_goTypes = nil
	file_connection_v1_hub_auth_proto_depIdxs = nil
}
