// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: connection/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_connection_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_connection_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CommandResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Telemetry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	State     string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	DeviceId  string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Telemetry_BoolValue
	//	*Telemetry_StringValue
	//	*Telemetry_IntValue
	//	*Telemetry_FloatValue
	Value         isTelemetry_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_connection_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_connection_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Telemetry) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Telemetry) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Telemetry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Telemetry) GetValue() isTelemetry_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Telemetry) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Telemetry_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Telemetry) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Telemetry_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Telemetry) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Telemetry_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Telemetry) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*Telemetry_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

type isTelemetry_Value interface {
	isTelemetry_Value()
}

type Telemetry_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Telemetry_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Telemetry_IntValue struct {
	IntValue int64 `protobuf:"varint,6,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Telemetry_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,7,opt,name=float_value,json=floatValue,proto3,oneof"`
}

func (*Telemetry_BoolValue) isTelemetry_Value() {}

func (*Telemetry_StringValue) isTelemetry_Value() {}

func (*Telemetry_IntValue) isTelemetry_Value() {}

func (*Telemetry_FloatValue) isTelemetry_Value() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds uint64                 `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_connection_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_connection_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// Message sent by the hub to the cloud.
type HubMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*HubMessage_CommandResult
	//	*HubMessage_Heartbeat
	//	*HubMessage_Telemetry
	Message       isHubMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubMessage) Reset() {
	*x = HubMessage{}
	mi := &file_connection_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessage) ProtoMessage() {}

func (x *HubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessage.ProtoReflect.Descriptor instead.
func (*HubMessage) Descriptor() ([]byte, []int) {
	return file_connection_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *HubMessage) GetMessage() isHubMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *HubMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Message.(*HubMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *HubMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*HubMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *HubMessage) GetTelemetry() *Telemetry {
	if x != nil {
		if x, ok := x.Message.(*HubMessage_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

type isHubMessage_Message interface {
	isHubMessage_Message()
}

type HubMessage_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,1,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type HubMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type HubMessage_Telemetry struct {
	Telemetry *Telemetry `protobuf:"bytes,3,opt,name=telemetry,proto3,oneof"`
}

func (*HubMessage_CommandResult) isHubMessage_Message() {}

func (*HubMessage_Heartbeat) isHubMessage_Message() {}

func (*HubMessage_Telemetry) isHubMessage_Message() {}

var File_connection_v1_messages_proto protoreflect.FileDescriptor

const file_connection_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1cconnection/v1/messages.proto\x12\rconnection.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\rCommandResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\"\x89\x02\n" +
	"\tTelemetry\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x06 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\a \x01(\x02H\x00R\n" +
	"floatValueB\a\n" +
	"\x05value\"2\n" +
	"\tHeartbeat\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x04R\ruptimeSeconds\"\xd2\x01\n" +
	"\n" +
	"HubMessage\x12E\n" +
	"\x0ecommand_result\x18\x01 \x01(\v2\x1c.connection.v1.CommandResultH\x00R\rcommandResult\x128\n" +
	"\theartbeat\x18\x02 \x01(\v2\x18.connection.v1.HeartbeatH\x00R\theartbeat\x128\n" +
	"\ttelemetry\x18\x03 \x01(\v2\x18.connection.v1.TelemetryH\x00R\ttelemetryB\t\n" +
	"\amessageB3Z1github.com/ship-monitor/protocol/go/connection/v1b\x06proto3"

var (
	file_connection_v1_messages_proto_rawDescOnce sync.Once
	file_connection_v1_messages_proto_rawDescData []byte
)

func file_connection_v1_messages_proto_rawDescGZIP() []byte {
	file_connection_v1_messages_proto_rawDescOnce.Do(func() {
		file_connection_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connection_v1_messages_proto_rawDesc), len(file_connection_v1_messages_proto_rawDesc)))
	})
	return file_connection_v1_messages_proto_rawDescData
}

var file_connection_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_connection_v1_messages_proto_goTypes = []any{
	(*CommandResult)(nil),         // 0: connection.v1.CommandResult
	(*Telemetry)(nil),             // 1: connection.v1.Telemetry
	(*Heartbeat)(nil),             // 2: connection.v1.Heartbeat
	(*HubMessage)(nil),            // 3: connection.v1.HubMessage
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_connection_v1_messages_proto_depIdxs = []int32{
	4, // 0: connection.v1.Telemetry.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: connection.v1.HubMessage.command_result:type_name -> connection.v1.CommandResult
	2, // 2: connection.v1.HubMessage.heartbeat:type_name -> connection.v1.Heartbeat
	1, // 3: connection.v1.HubMessage.telemetry:type_name -> connection.v1.Telemetry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_connection_v1_messages_proto_init() }
func file_connection_v1_messages_proto_init() {
	if File_connection_v1_messages_proto != nil {
		return
	}
	file_connection_v1_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*Telemetry_BoolValue)(nil),
		(*Telemetry_StringValue)(nil),
		(*Telemetry_IntValue)(nil),
		(*Telemetry_FloatValue)(nil),
	}
	file_connection_v1_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*HubMessage_CommandResult)(nil),
		(*HubMessage_Heartbeat)(nil),
		(*HubMessage_Telemetry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connection_v1_messages_proto_rawDesc), len(file_connection_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connection_v1_messages_proto_goTypes,
		DependencyIndexes: file_connection_v1_messages_proto_depIdxs,
		MessageInfos:      file_connection_v1_messages_proto_msgTypes,
	}.Build()
	File_connection_v1_messages_proto = out.File
	file_connection_v1_messages_proto_goTypes = nil
	file_connection_v1_messages_proto_depIdxs = nil
}
