// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: connection/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_connection_v1_service_proto protoreflect.FileDescriptor

const file_connection_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bconnection/v1/service.proto\x12\rconnection.v1\x1a%connection/v1/connected_devices.proto\x1a\x1cconnection/v1/messages.proto\x1a#connection/v1/server_messages.proto2\xbc\x01\n" +
	"\x11ConnectionService\x12F\n" +
	"\aConnect\x12\x19.connection.v1.HubMessage\x1a\x1c.connection.v1.ServerMessage(\x010\x01\x12_\n" +
	"\x12ConnectDeviceToHub\x12#.connection.v1.ConnectDeviceRequest\x1a$.connection.v1.ConnectDeviceResponseB3Z1github.com/ship-monitor/protocol/go/connection/v1b\x06proto3"

var file_connection_v1_service_proto_goTypes = []any{
	(*HubMessage)(nil),            // 0: connection.v1.HubMessage
	(*ConnectDeviceRequest)(nil),  // 1: connection.v1.ConnectDeviceRequest
	(*ServerMessage)(nil),         // 2: connection.v1.ServerMessage
	(*ConnectDeviceResponse)(nil), // 3: connection.v1.ConnectDeviceResponse
}
var file_connection_v1_service_proto_depIdxs = []int32{
	0, // 0: connection.v1.ConnectionService.Connect:input_type -> connection.v1.HubMessage
	1, // 1: connection.v1.ConnectionService.ConnectDeviceToHub:input_type -> connection.v1.ConnectDeviceRequest
	2, // 2: connection.v1.ConnectionService.Connect:output_type -> connection.v1.ServerMessage
	3, // 3: connection.v1.ConnectionService.ConnectDeviceToHub:output_type -> connection.v1.ConnectDeviceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_connection_v1_service_proto_init() }
func file_connection_v1_service_proto_init() {
	if File_connection_v1_service_proto != nil {
		return
	}
	file_connection_v1_connected_devices_proto_init()
	file_connection_v1_messages_proto_init()
	file_connection_v1_server_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connection_v1_service_proto_rawDesc), len(file_connection_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connection_v1_service_proto_goTypes,
		DependencyIndexes: file_connection_v1_service_proto_depIdxs,
	}.Build()
	File_connection_v1_service_proto = out.File
	file_connection_v1_service_proto_goTypes = nil
	file_connection_v1_service_proto_depIdxs = nil
}
