// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: connection/v1/server_messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specific only for v1.
// Message for setting sensor configuration
type SetSensorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	MinTemp       float32                `protobuf:"fixed32,2,opt,name=min_temp,json=minTemp,proto3" json:"min_temp,omitempty"`
	MaxTemp       float32                `protobuf:"fixed32,3,opt,name=max_temp,json=maxTemp,proto3" json:"max_temp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSensorConfig) Reset() {
	*x = SetSensorConfig{}
	mi := &file_connection_v1_server_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSensorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSensorConfig) ProtoMessage() {}

func (x *SetSensorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_server_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSensorConfig.ProtoReflect.Descriptor instead.
func (*SetSensorConfig) Descriptor() ([]byte, []int) {
	return file_connection_v1_server_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SetSensorConfig) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetSensorConfig) GetMinTemp() float32 {
	if x != nil {
		return x.MinTemp
	}
	return 0
}

func (x *SetSensorConfig) GetMaxTemp() float32 {
	if x != nil {
		return x.MaxTemp
	}
	return 0
}

type RunCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier to receive the result of the command
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Command name
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// Arguments
	Args          map[string]string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommand) Reset() {
	*x = RunCommand{}
	mi := &file_connection_v1_server_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommand) ProtoMessage() {}

func (x *RunCommand) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_server_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommand.ProtoReflect.Descriptor instead.
func (*RunCommand) Descriptor() ([]byte, []int) {
	return file_connection_v1_server_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RunCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunCommand) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

// Message sent by the cloud to the hub.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_RunCommand
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_connection_v1_server_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_server_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_connection_v1_server_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetRunCommand() *RunCommand {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_RunCommand); ok {
			return x.RunCommand
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_RunCommand struct {
	RunCommand *RunCommand `protobuf:"bytes,1,opt,name=run_command,json=runCommand,proto3,oneof"`
}

func (*ServerMessage_RunCommand) isServerMessage_Message() {}

var File_connection_v1_server_messages_proto protoreflect.FileDescriptor

const file_connection_v1_server_messages_proto_rawDesc = "" +
	"\n" +
	"#connection/v1/server_messages.proto\x12\rconnection.v1\"d\n" +
	"\x0fSetSensorConfig\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bmin_temp\x18\x02 \x01(\x02R\aminTemp\x12\x19\n" +
	"\bmax_temp\x18\x03 \x01(\x02R\amaxTemp\"\xa8\x01\n" +
	"\n" +
	"RunCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x127\n" +
	"\x04args\x18\x03 \x03(\v2#.connection.v1.RunCommand.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\rServerMessage\x12<\n" +
	"\vrun_command\x18\x01 \x01(\v2\x19.connection.v1.RunCommandH\x00R\n" +
	"runCommandB\t\n" +
	"\amessageB3Z1github.com/ship-monitor/protocol/go/connection/v1b\x06proto3"

var (
	file_connection_v1_server_messages_proto_rawDescOnce sync.Once
	file_connection_v1_server_messages_proto_rawDescData []byte
)

func file_connection_v1_server_messages_proto_rawDescGZIP() []byte {
	file_connection_v1_server_messages_proto_rawDescOnce.Do(func() {
		file_connection_v1_server_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connection_v1_server_messages_proto_rawDesc), len(file_connection_v1_server_messages_proto_rawDesc)))
	})
	return file_connection_v1_server_messages_proto_rawDescData
}

var file_connection_v1_server_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_connection_v1_server_messages_proto_goTypes = []any{
	(*SetSensorConfig)(nil), // 0: connection.v1.SetSensorConfig
	(*RunCommand)(nil),      // 1: connection.v1.RunCommand
	(*ServerMessage)(nil),   // 2: connection.v1.ServerMessage
	nil,                     // 3: connection.v1.RunCommand.ArgsEntry
}
var file_connection_v1_server_messages_proto_depIdxs = []int32{
	3, // 0: connection.v1.RunCommand.args:type_name -> connection.v1.RunCommand.ArgsEntry
	1, // 1: connection.v1.ServerMessage.run_command:type_name -> connection.v1.RunCommand
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_connection_v1_server_messages_proto_init() }
func file_connection_v1_server_messages_proto_init() {
	if File_connection_v1_server_messages_proto != nil {
		return
	}
	file_connection_v1_server_messages_proto_msgTypes[2].OneofWrappers = []any{
		(*ServerMessage_RunCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connection_v1_server_messages_proto_rawDesc), len(file_connection_v1_server_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connection_v1_server_messages_proto_goTypes,
		DependencyIndexes: file_connection_v1_server_messages_proto_depIdxs,
		MessageInfos:      file_connection_v1_server_messages_proto_msgTypes,
	}.Build()
	File_connection_v1_server_messages_proto = out.File
	file_connection_v1_server_messages_proto_goTypes = nil
	file_connection_v1_server_messages_proto_depIdxs = nil
}
