// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: connection/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionService_Connect_FullMethodName            = "/connection.v1.ConnectionService/Connect"
	ConnectionService_ConnectDeviceToHub_FullMethodName = "/connection.v1.ConnectionService/ConnectDeviceToHub"
	ConnectionService_AuthenticateHub_FullMethodName    = "/connection.v1.ConnectionService/AuthenticateHub"
	ConnectionService_RefreshHubAuth_FullMethodName     = "/connection.v1.ConnectionService/RefreshHubAuth"
)

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Handles connections between the hub and the client.
type ConnectionServiceClient interface {
	// Connect establish connection on which hub and cloud will communicate.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HubMessage, ServerMessage], error)
	// ConnectDeviceToMe requests the cloud to connect device to the hub.
	ConnectDeviceToHub(ctx context.Context, in *ConnectDeviceRequest, opts ...grpc.CallOption) (*ConnectDeviceResponse, error)
	// Authenticates hub on first time connect.
	AuthenticateHub(ctx context.Context, in *AuthenticateHubRequest, opts ...grpc.CallOption) (*AuthenticateHubResponse, error)
	// Refresh hub authentication.
	RefreshHubAuth(ctx context.Context, in *RefreshHubAuthRequest, opts ...grpc.CallOption) (*RefreshHubAuthResponse, error)
}

type connectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionServiceClient(cc grpc.ClientConnInterface) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HubMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectionService_ServiceDesc.Streams[0], ConnectionService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HubMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionService_ConnectClient = grpc.BidiStreamingClient[HubMessage, ServerMessage]

func (c *connectionServiceClient) ConnectDeviceToHub(ctx context.Context, in *ConnectDeviceRequest, opts ...grpc.CallOption) (*ConnectDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectDeviceResponse)
	err := c.cc.Invoke(ctx, ConnectionService_ConnectDeviceToHub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) AuthenticateHub(ctx context.Context, in *AuthenticateHubRequest, opts ...grpc.CallOption) (*AuthenticateHubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateHubResponse)
	err := c.cc.Invoke(ctx, ConnectionService_AuthenticateHub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) RefreshHubAuth(ctx context.Context, in *RefreshHubAuthRequest, opts ...grpc.CallOption) (*RefreshHubAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshHubAuthResponse)
	err := c.cc.Invoke(ctx, ConnectionService_RefreshHubAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
// All implementations must embed UnimplementedConnectionServiceServer
// for forward compatibility.
//
// Handles connections between the hub and the client.
type ConnectionServiceServer interface {
	// Connect establish connection on which hub and cloud will communicate.
	Connect(grpc.BidiStreamingServer[HubMessage, ServerMessage]) error
	// ConnectDeviceToMe requests the cloud to connect device to the hub.
	ConnectDeviceToHub(context.Context, *ConnectDeviceRequest) (*ConnectDeviceResponse, error)
	// Authenticates hub on first time connect.
	AuthenticateHub(context.Context, *AuthenticateHubRequest) (*AuthenticateHubResponse, error)
	// Refresh hub authentication.
	RefreshHubAuth(context.Context, *RefreshHubAuthRequest) (*RefreshHubAuthResponse, error)
	mustEmbedUnimplementedConnectionServiceServer()
}

// UnimplementedConnectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionServiceServer struct{}

func (UnimplementedConnectionServiceServer) Connect(grpc.BidiStreamingServer[HubMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedConnectionServiceServer) ConnectDeviceToHub(context.Context, *ConnectDeviceRequest) (*ConnectDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectDeviceToHub not implemented")
}
func (UnimplementedConnectionServiceServer) AuthenticateHub(context.Context, *AuthenticateHubRequest) (*AuthenticateHubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateHub not implemented")
}
func (UnimplementedConnectionServiceServer) RefreshHubAuth(context.Context, *RefreshHubAuthRequest) (*RefreshHubAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshHubAuth not implemented")
}
func (UnimplementedConnectionServiceServer) mustEmbedUnimplementedConnectionServiceServer() {}
func (UnimplementedConnectionServiceServer) testEmbeddedByValue()                           {}

// UnsafeConnectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionServiceServer will
// result in compilation errors.
type UnsafeConnectionServiceServer interface {
	mustEmbedUnimplementedConnectionServiceServer()
}

func RegisterConnectionServiceServer(s grpc.ServiceRegistrar, srv ConnectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedConnectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionService_ServiceDesc, srv)
}

func _ConnectionService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnectionServiceServer).Connect(&grpc.GenericServerStream[HubMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionService_ConnectServer = grpc.BidiStreamingServer[HubMessage, ServerMessage]

func _ConnectionService_ConnectDeviceToHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).ConnectDeviceToHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_ConnectDeviceToHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).ConnectDeviceToHub(ctx, req.(*ConnectDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_AuthenticateHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateHubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).AuthenticateHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_AuthenticateHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).AuthenticateHub(ctx, req.(*AuthenticateHubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_RefreshHubAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshHubAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).RefreshHubAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_RefreshHubAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).RefreshHubAuth(ctx, req.(*RefreshHubAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionService_ServiceDesc is the grpc.ServiceDesc for ConnectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connection.v1.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectDeviceToHub",
			Handler:    _ConnectionService_ConnectDeviceToHub_Handler,
		},
		{
			MethodName: "AuthenticateHub",
			Handler:    _ConnectionService_AuthenticateHub_Handler,
		},
		{
			MethodName: "RefreshHubAuth",
			Handler:    _ConnectionService_RefreshHubAuth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ConnectionService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connection/v1/service.proto",
}
