syntax = "proto3";

package connection.v1;

option go_package = "github.com/ship-monitor/protocol/go/connection/v1";

enum ConnectionError {
  CONNECTION_ERROR_UNKNOWN = 0;
  CONNECTION_ERROR_HUB_NOT_AUTHENTICATED = 1;
  CONNECTION_ERROR_INTERNAL = 2;
}

message ConnectDeviceRequest {
  string device_id = 1;

  // Device secret used for authentication.
  // Every device must have secret from which it generates 30s last auth key, thats checked on cloud.
  string device_key = 2;
}

message ConnectDeviceResponse {
  bool approved = 1;
  optional ConnectionError error = 2;
}
